In [11]:
# Importing NumPy library
import numpy as np

In [13]:
# Creating a NumPy array
numbers = np.array([10, 20, 30, 40, 50])

# Displaying the array
print("Array:", numbers)

Array: [10 20 30 40 50]


In [15]:
# Calculate the mean, min, max and of the array using built-in functions of numpy
mean_value = np.mean(numbers)
max_value = np.max(numbers)
min_value = np.min(numbers)
sum_value = np.sum(numbers)

# priniting each val
print("Mean:", mean_value)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)
print("Sum:", sum_value)

Mean: 30.0
Maximum Value: 50
Minimum Value: 10
Sum: 150


In [16]:
# Create the first and second array
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print("Array 1:", arr_1)
print("Array 2:", arr_2)

Array 1: [1 2 3]
Array 2: [4 5 6]


In [18]:
# Adding corresponding elements of both arrays
addition_result = arr_1 + arr_2

# Multiplying corresponding elements of both arrays
multiplication_result = arr_1 * arr_2

print("Addition Result:", addition_result)
print("Multiplication Result:", multiplication_result)

Addition Result: [5 7 9]
Multiplication Result: [ 4 10 18]


In [19]:
# Creating a 3x3 matrix using NumPy
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("3x3 Matrix:")
print(matrix)

3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
